export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  PARENT: {
    ROOT: "/parent",
    DASHBOARD: "/parent",
    LIBRARY: "/parent/library",
    CHILDREN: "/parent/children",
    FAMILY_CHARACTERS: "/parent/family-characters",
    STUDIO: "/parent/studio",
    EQ_JOURNEY: "/parent/eq-journey",
    MARKETPLACE: "/parent/marketplace",
    BILLING: "/parent/billing",
    HELP: "/parent/help",
    SETTINGS: "/parent/settings",
  },
  MODERATOR: {
    ROOT: "/moderator",
    DASHBOARD: "/moderator",
    SELLER_APPLICATIONS: "/moderator/seller-applications",
    QUEUE: "/moderator/queue",
    WORKSPACE: "/moderator/workspace",
    workspace: (storyId) => `/moderator/workspace/${storyId}`,
    TOPICS: "/moderator/topics",
    BACKGROUNDS: "/moderator/backgrounds",
    REPORTS: "/moderator/reports",
    SUSPENDED: "/moderator/suspended",
    STRIKES: "/moderator/strikes",
    AUDITS: "/moderator/audits",
    AI_FLAGS: "/moderator/ai-flags",
    KEYWORDS: "/moderator/keywords",
    GUIDELINES: "/moderator/guidelines",
  },
  KID: {
    ROOT: "/kid",
    READER: "/kid/story",
    story: (storyId) => `/kid/story/${storyId}`,
    BOOKSHELF: "/kid/bookshelf",
  },
  ADMIN: {
    ROOT: "/admin",
    DASHBOARD: "/admin",
    ACCOUNTS: "/admin/accounts",
    PLANS: "/admin/plans",
    AI_CONFIG: "/admin/ai-config",
    WITHDRAWALS: "/admin/withdrawals",
    REFUNDS: "/admin/refunds",
    REVENUE: "/admin/revenue",
    AI_COSTS: "/admin/ai-costs",
    PROFIT_LOSS: "/admin/profit-loss",
    APPEALS: "/admin/appeals",
    AUDIT_LOGS: "/admin/audit-logs",
  },
};
